version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
        
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - run: make docker_build
      - run:
          name: Docker Login and Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $USERNAME --password-stdin
            docker tag hello-world-printer $USERNAME/hello-world-printer-k7-2026
            docker push $USERNAME/hello-world-printer-k7-2026
            docker logout